pipeline {
    agent any

    tools {
        jdk 'JDK-17'
        maven 'Maven-3.9'
    }

    environment {
        DB_URL = 'jdbc:postgresql://localhost:5432/qa-testsphere'
        DB_USER = 'postgres'
        DB_PASSWORD = 'postgres123'
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Verify Tools') {
            steps {
                bat 'java -version'
                bat 'mvn -version'
            }
        }

        stage('Start Backend') {
    steps {
                dir('backend') {
                    bat '''
                    echo Starting backend...
                    start /B node server.js
            REM wait for backend to be reachable
            ping -n 6 127.0.0.1 > nul
            '''
        }
    }
}


        stage('Run Automated Tests') {
            steps {
                dir('automation-testing') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution finished'
            archiveArtifacts artifacts: '**/target/surefire-reports/*.xml', allowEmptyArchive: true
        }
        success {
            echo 'BUILD SUCCESS: All tests passed'
        }
        failure {
            echo 'BUILD FAILED: Some tests failed'
        }
    }
}
